AWSTemplateFormatVersion: '2010-09-09'

Description: HireTalent24 static website infrastructure

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hiretalent24.com
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

Outputs:

  WebsiteBucketName:
    Description: HireTalent24 website S3 bucket
    Value: !Ref WebsiteBucket